CREATE TABLE common (
       id VARCHAR PRIMARY KEY,
       attachment VARCHAR,
       attributed_to VARCHAR,
       audience VARCHAR,
       context VARCHAR NOT NULL DEFAULT 'https://www.w3e.org/ns/activitystreams',
       content VARCHAR,
       content_map VARCHAR,
       "name" VARCHAR,
       name_map VARCHAR,
       end_time VARCHAR,
       generator VARCHAR,
       icon VARCHAR,
       image VARCHAR,
       in_reply_to VARCHAR,
       location VARCHAR,
       preview VARCHAR,
       published VARCHAR,
       replies VARCHAR,
       start_time VARCHAR,
       summary VARCHAR,
       summary_map VARCHAR,
       tag VARCHAR,
       updated VARCHAR,
       url VARCHAR,
       "to" VARCHAR,
       bto VARCHAR,
       cc VARCHAR,
       bcc VARCHAR,
       media_type VARCHAR,
       duration VARCHAR,
       ap_type VARCHAR
)
