#[derive(Queryable)]
pub struct Common {
    pub id: String,
    pub attachment: String,
    pub attributed_to: String,
    pub audience: String,
    pub context: String,
    pub content: String,
    pub content_map: String,
    pub name: String,
    pub name_map: String,
    pub end_time: String,
    pub generator: String,
    pub icon: String,
    pub image: String,
    pub in_reply_to: String,
    pub location: String,
    pub preview: String,
    pub published: String,
    pub replies: String,
    pub start_time: String,
    pub summary: String,
    pub summary_map: String,
    pub tag: String,
    pub updated: String,
    pub url: String,
    pub to: String,
    pub bto: String,
    pub cc: String,
    pub bcc: String,
    pub media_type: String,
    pub duration: String,
    pub ap_type: String,
}
